apiVersion: v1
kind: Pod
metadata:
  name: volumes
spec:
  containers:
    -
      image: ubuntu
      command: 
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: ubuntu
      volumeMounts:
        -
          mountPath: /data
          name: data
    -
      image: centos
      command: 
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: centos
      volumeMounts:
        -
          mountPath: /data
          name: data
  volumes: 
    -
      name: data
      emptyDir: {}
